site_name: Hazard Waste Systems
site_description: Documentation for the HazSystems example application
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/dpgraham4401/hazsystems
edit_uri: /blob/main/docs/docs/
plugins:
  - privacy:
  - search:
theme:
  name: material
  # https://squidfunk.github.io/mkdocs-material/customization/
  custom_dir: docs/overrides
extra_javascript:
    - javascript/readthedocs.js