site_name: Hazard Waste Systems
site_description: Documentation for the HazSystems example application
site_url: https://dpgraham4401.github.com/hazsystems
repo_url: https://github.com/dpgraham4401/hazsystems
edit_uri: /blob/main/docs/docs/
plugins:
  - privacy:
  - search:
theme:
  name: material