name: Automate Release
# This workflow is responsible for merging 'main' (along with any tags) into 'deploy' upon the publication of a release.

permissions:
  contents: write

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  merge-main-into-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action [bot]"

      - name: display github object info
        run: |
            echo "github: ${{ toJson(github) }}"

      - name: Merge main into deploy
        run: |
          git switch origin/deploy
          git merge origin/main --ff-only -m "Merge main into deploy following release ${{ github.event.release.tag_name }}"
          git push origin deploy --follow-tags